logging:
  level:
    root: WARN
    org:
      springframework:
      hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG
  file: mylogfile.log
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  debug: true
